name: Sikkerhet

on:
  push:
    branches:
      - main

env:
  GITHUB_USERNAME: x-access-token
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  app-dependencies-vulnerabilities:
    name: Skanner applikasjon for sårbarheter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle@master
        with:
          command: monitor
          args: --org=po-utbetaling --project-name=${{ github.repository }} --remote-repo-url=https://github.com/${{ github.repository }}.git
          json: true